### ISSUE TITLE
crates.io first release to-do list

### ISSUE THREAD

**Issue by jeanmanguy** [jeanmanguy/aa-regex#1]
- [ ] basic functionalities
- [ ] up to date tests
- [ ] up to date doc
- [ ] up to date examples
- [ ] bump version
- [ ] update README
